- README.md
The proxy link is broken and the fix is now pointing to the correct location.
> Update README.md - Fix for Proxy Link

- README.md
Reverts cloudfoundry/cf-mysql-release#57
I'm sorry, I had to revert this. I merged it against master, which was incorrect.
This pull request has been reviewed, and it sounds good. BUT, it's filed against the wrong branch - it should be filed against develop, not master. We've only just published a [CONTRIBUTING](https://github.com/cloudfoundry/cf-mysql-release/blob/develop/CONTRIBUTING.md) file, please check it out.
If you could please retract this PR, and re-submit it against develop, I'll be very grateful.
--
Marco Nicosia
Product Manager
Pivotal Software, Inc.
> Revert "Update README.md - Fix for Proxy Link"

- generate_deployment_manifest
On some versions of bash shift command fails with error "shift: can't shift that many" when no args were given, so user gets error instead of usage info.
Test script:
```
#!/bin/bash
echo "Before shift:" $@
shift
echo "After shift:" $@
```
Bash 3.2.57, Mac OS 10.10
```
$ sh test.sh 1 2 3
Before shift: 1 2 3
After shift: 2 3
$ sh test.sh 
Before shift:
After shift:
Bash 4.3.11, Ubuntu 14.04:
```
```
$ sh test.sh 1 2 3
Before shift: 1 2 3
After shift: 2 3
$ sh test.sh 
Before shift:
test.sh: 4: shift: can't shift that many
```
> Generate deployment manifest script: shift arguments after infrastrucure check

- docs/arbitrator.md
Yesterday, partially based on these instructions, I accidentally gave `generate-deployment-manifest` my actual cf-release manifest. I don't think that's what we want here. In cf-mysql-release we provide a `cf-stub.yml` which an operator should be providing for both (I think) bosh-lite and IaaS-based invocations of `generate-deployment-manifest`?
[#114036369]
> Update generate-deployment-manifest to refer to cf-stubs

- docs/Known-Issues.md
Update Known Issues to explain that v26 no longer builds from source.
Please additionally tag this commit as `v26` so that it will show up to anyone who has limited scope to v26. Thanks!
> v26 broken dependency

- jobs/mysql/spec
- jobs/proxy/spec
- packages/mariadb/packaging
I have a few changes to reduce disk usage in this component:
* mysql and proxy jobs don't need golang during runtime
* The mysql-test dir is over 300MB and isn't used during runtime
* Stripping the mysql binaries reduces their size from 304M -> 132M
If the changes aren't closely related enough, I'd be happy to split them into separate PRs for discussion.
> Trim release size

- manifest-generation/cf-mysql-template.yml
- manifest-generation/examples/aws/iaas-settings.yml
- manifest-generation/examples/vsphere/iaas-settings.yml
Some Iaas fail with too large concurrent compilation workers. This enables configuring them without manually patching the generated manifest.
> Add ability to override number of compilation workers

- manifest-generation/cf-mysql-template.yml
- manifest-generation/examples/property-overrides.yml
For our migration from v25 to v26, we had difficulties with deployment name hard coded. This patch adds the ability to set a personalized deployment name. The property property_overrides.deployment_name does not have to be defined (in this case, it's like the old behaviour).
> Add ability to override deployment name

- manifest-generation/cf-mysql-template.yml
- manifest-generation/misc-templates/config-from-cf-internal.yml
- manifest-generation/misc-templates/config-from-cf.yml
* `admin_username` and `admin_password` come from property overrides now
* use `properties.system_domain` instead of the deprecated and removed
`properties.domain`
* use the `properties.cc.srv_api_uri` from cf instead of constructing it
Signed-off-by: Andrew Edgar <aedgar@ca.ibm.com>
> `./scripts/generate-deployment-manifest` now takes a real cf manifest

- jobs/mysql/spec
- jobs/mysql/templates/my.cnf.erb
When you are able to override the innodb_buffer_pool_size you should also have the ability to override the innobd_buffer_pool_instances.
The rule of thumb is if the size is > 1GB you want the number of instances where size / instances is >= 1GB.
> Allow for override of the innodb_buffer_pool_instances

- manifest-generation/examples/azure/iaas-settings.yml
This new example using the existing AWS and vSphere examples as a
template, but updates them with Azure specific cloud_properties.
> Add Azure iaas-settings Example

- jobs/mysql/templates/mariadb_ctl_config.yml.erb
- jobs/mysql/templates/my.cnf.erb
As the arbitrator is not necessary it should be optional to define one.
Signed-off-by: Adrian Kurt <adrian.kurt@swisscom.com>
> Arbitrator should be optional

- jobs/verify-cluster-schemas/spec
- jobs/verify-cluster-schemas/templates/run.rb.erb
Errand verify-cluster-schemas should be able to use bosh links.
Arbitrator should be optional.
Signed-off-by: Adrian Kurt <adrian.kurt@swisscom.com>
> verify-cluster-schemas errand is now using bosh links

- manifest-generation/cf-mysql-template-v2.yml
- adhere to default cloud config guidelines (all cc resources are named `default`)
- use iaas agnostic persistent disk declaration
- remove static_ips
> simplify bosh template

- src/cf-mysql-common/pid_utils.sh
The default SIGTERM is sent when killing the PID.
> Update comments for kill_and_wait()

- jobs/mysql/spec
- jobs/mysql/templates/mariadb_ctl_config.yml.erb
- jobs/mysql/templates/my.cnf.erb
Currently the mysql host is assumed to be the same as the default
network host. This change allows deploy-time selection of the
main mysql host for a cluster.
Call discover_external_ip only if there's no
cf_mysql.mysql.advertise_host config value.
> Allow the main mysql host to be specified via config.

- config/blobs.yml
- packages/xtrabackup/packaging
This fixes #143 by bumping the socat version to 1.7.3.1
This was tested by running the smoke-tests on bosh-lite. Additionally I did a deployment of `cf-deployment` to AWS, using the default stemcell as well as our custom built openSUSE stemcell. 
The URL of the new blob is: http://www.dest-unreach.org/socat/download/socat-1.7.3.1.tar.gz
I'm not sure about the second commit, adding the URL as comment in the `config/blobs.yml`.
> Upgrade socat version

- jobs/smoke-tests/spec
- jobs/smoke-tests/templates/config.yml.erb
https://www.pivotaltracker.com/story/show/138070221
Signed-off-by: Dan Wendorf <dwendorf@pivotal.io>
> Optionally consume cc link for app_domains in smoke tests

- scripts/download-logs
It is convenient to have an option which allows passing in the ssh private key manually in cases were ssh-agent is not running and user does not prefer to install the key into the keychain.
> add private key option to download-logs script

- manifest-generation/examples/job-overrides-consul.yml
Once consul-release consumes its own link, the consul_agent will fail to
come up due to the job duplication (that we do to acheive AZs). The
error looks something like the one here: https://diego.ci.cf-app.com/teams/main/pipelines/main/jobs/ketchup-mysql-deploy/builds/216
> Nil the consul link in the example stub

- packages/galera/packaging
The tests don't actually give much value (they're more useful when modifying the source code of the package, not when rebuilding known-good source code).  Worse, some of the tests are timing-dependent.  See also upstream's `GALERA_TEST_DETERMINISTIC` flag.
Disabling the tests should not affect the output of the build.
> Disable running tests when packaging galera

- README.md
It was missing a scheme, and would result in a GitHub 404.
> Fix link to instructions for deploying release

- jobs/mysql/spec
- jobs/mysql/templates/mariadb_ctl_config.yml.erb
Thanks for opening a PR. Please make sure you've read and followed the [Contributing guide](https://github.com/cloudfoundry/cf-mysql-release/blob/develop/CONTRIBUTING.md), including signing the Contributor License Agreement.
It provides a way to disable bootstrap for the first instance in an instance group
I am using multi-cpi feature of bosh to deploy mysql cluster in 2 separate vsphere datacenters. Because of the fact that I use 2 separate datacenters, I have to split the mysql instance group into 2 separate instance groups, where each group is configured with its own AS and bosh network. I use a manual link to prepare `mysql` link in such a way that it contains combined set of all ips from both instance groups. However, I still need to disable bootstrap on the first instance of the …
> Add `cf_mysql.mysql.bootstrap_enabled` property

- jobs/mysql/templates/mariadb_ctl.erb
Thanks for opening a PR. Please make sure you've read and followed the [Contributing guide](https://github.com/cloudfoundry/cf-mysql-release/blob/develop/CONTRIBUTING.md), including signing the Contributor License Agreement.
This PR fixes an issue where the mariadb_ctl script incorrectly exits with "Exiting for restart because IPsec is present but not yet running" message if the vm hostname contain "ipsec"
Command to check IPsec job is `/var/vcap/bosh/bin/monit summary | grep ipsec` is too permissive. In our case it captured `System 'system_vm-b7770176-d990-4543-64af-3f9439760ba8.c.cf-xxx-xxx-ipsec.internal' running`
> Tighten up IPsec monit check

- jobs/cf-mysql-broker/templates/settings.yml.erb
If a price is associated with a plan,the "**free**" field must be fill with the value "**false**" in the section "**plan of the service**" in the deployment manifest. 
This information must be sent from the manifest to the Mysql broker via the `**setting.yml**` file.
This PR adjusts the script code **setting.yml.erb** to meet the need.
This PR is associated with the #22 PR of cf-mysql-broker
> Manage paid and free plan

- jobs/cf-mysql-broker/templates/settings.yml.erb
Currently, the MySql release does not display the price associated with a plan in a currency other than **USD**.
The currency information is not correctly passed from the deployment manifest to the **setting.ym**l file in the config of the cf-mysql-broker job.
This PR resolves this dysfunction
> Manage currencies other than Usd
